
db_server:
  restart: always
  image: f2hex/postgres
  container_name: redmine-db-server
  volumes:
    - /data/redmine/db:/var/lib/postgresql/data

app_server:
  restart: always
  image: f2hex/redmine
  container_name: redmine-app-server
  volumes:
    - /data/redmine/app/files:/usr/src/redmine/files

web_server:
  restart: always
  image: f2hex/nginx
  container_name: redmine-web-server
  ports:
    - "8081:8081"
  volumes:
    - /data/redmine/web/log:/var/log/nginx
 

